name: .NET Framework Desktop

on:
  push:
    paths:
      - "ExampleWPFProject/**"
      - ".github/workflows/Build.yml"
  pull_request:
    paths:
      - "ExampleWPFProject/**"
      - ".github/workflows/Build.yml"
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Test_Project_Path: ExampleWPFProject\ExampleWPFProject.csproj 
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ${{ env.Test_Project_Path }}

    - name: Build the project
      run: msbuild ${{ env.Test_Project_Path }} /p:Configuration=${{ matrix.configuration }}

    - name: Execute unit tests
      run: msbuild ${{ env.Test_Project_Path }} /t:VSTest /p:Configuration=${{ matrix.configuration }}
