name: .NET Framework Desktop

on:
  push:
    paths:
      - "ExampleWPFProject/**"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "ExampleWPFProject/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Name_Project: ExampleWPFProject
      Test_Project_Path: ExampleWPFProject/ExampleWPFProject.csproj 
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Build the project
      run: msbuild ${{ env.Test_Project_Path }} /p:Configuration=${{ matrix.configuration }}

    - name: Upload a Build Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}-Windows
        path: ExampleWPFProject/bin/${{ matrix.configuration }}/net48/${{ env.Name_Project }}.exe
