name: .NET Framework Desktop

on:
  push:
    paths:
      - "ExampleWPFProject/**"
      - ".github/workflows/Build.yml"
  pull_request:
    paths:
      - "ExampleWPFProject/**"
      - ".github/workflows/Build.yml"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    env:
      Project_File_Name: "ExampleWPFProject"
      Project_Folder_Name: "ExampleWPFProject"
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Install NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ${{ env.Project_Folder_Name }}/${{ env.Project_File_Name }}.csproj

    - name: Build the project
      run: msbuild ${{ env.Project_Folder_Name }}/${{ env.Project_File_Name }}.csproj /p:Configuration=${{ matrix.configuration }} /p:OutDir=public\

    - name: Upload a Build Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: ${{ env.Project_Folder_Name }}/public/
